name: Continuous Integration Docker

on:
  pull_request:
    branches:
      - docking-test
  workflow_dispatch: 
    inputs:
      image_name:
        description: 'Name of Docker image' 
        required: false

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.OSU_PIXELS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.OSU_PIXELS_DOCKERHUB_PASSWORD }}

      - name: Docker Login to GitLab Registry
        run: |
          docker login -u '${{ secrets.DOCKER_LOGIN_USERNAME}}' -p '${{ secrets.DOCKER_LOGIN_PASSWORD }}' gitlab-registry.cern.ch

      - name: Repo name
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BRANCH_NAME=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.event.inputs.image_name }}" >> $GITHUB_ENV
          fi

      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: osupixels/ph2_acf_gui_dev:${{ env.BRANCH_NAME }}
