name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: osupixels
          password: phase2pixels

      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: osupixels/ph2_acf_gui_dev:latest 
